#!python -i

def _set_env(input_path=''):
    import sys, os
    from pace_neutrons.utils import DetectMatlab, get_runtime_version, PaceConfiguration
    cf = PaceConfiguration()
    # If the environment variables are not set, we need to restart with execv
    DET = DetectMatlab(get_runtime_version())
    if DET.env_not_set():
        mlPath = DET.guess_path([input_path] + cf.CachedMatlabDirs)
        if not mlPath:
            if cf.IsFirstRun:
                from pace_neutrons.utils import install_MCR
                mlPath = install_MCR(interactive=True)
                cf.IsFirstRun = False
                cf.save()
            else:
                raise RuntimeError('Could not find Matlab MCR in known locations.\n' \
                                   'Please rerun with the option --matlab-dir to the MCR location.\n' \
                                   'This location will be cached for future lookup.\n' \
                                   'Alternatively, you can rerun with the --install-mcr option to install ' \
                                   'the compiler runtime.\n' \
                                   'This takes approximately 15-30min and will be silent\n')
        if cf.IsFirstRun:
            cf.IsFirstRun = False
            cf.save()
        DET.set_environment(mlPath)
        if input_path and input_path in mlPath:
            cf.CachedMatlabDirs = mlPath
            cf.save()
        args = [f'"{v}"' for v in [sys.executable]+sys.argv]
        if DET.system != 'Windows':
            os.execv(sys.executable, args)


def _get_args():
    import argparse
    parser = argparse.ArgumentParser(description='A wrapper script to run the PACE module')
    parser.add_argument('-d', '--matlab-dir', help='Directory where Matlab MCR is installed')
    parser.add_argument('-s', '--spyder', action='store_true', help='Runs under Spyder IDE')
    parser.add_argument('-j', '--jupyter', action='store_true', help='Runs in Jupyter notebook server')
    parser.add_argument('-m', '--mantid', action='store_true', help='Runs under Mantid Workbench')
    parser.add_argument('--install-mcr', action='store_true', help='Installs the Matlab MCR')
    return parser


def main(*args):
    try:
        args = _get_args().parse_args(args)
    except:
        if __name__ == '__main__' and ('-h' in args or '--help' in args):
            import sys
            sys.exit()
        else:
            raise RuntimeError(f'Invalid arguments {args}.')
    if sum([args.spyder, args.jupyter, args.mantid]) > 1:
        raise RuntimeError('You can only specify one of --spyder, --jupyter or --mantid')
    if args.install_mcr:
        from pace_neutrons.utils import install_MCR
        install_MCR(interactive=False)
    mlPath = args.matlab_dir if args.matlab_dir is not None else ''
    # Run set env first before any more imports because we might need to restart the process
    _set_env(mlPath)
    # Launches other environments if asked for
    if args.spyder:
        import sys
        sys.argv = ['']
        try:
            import spyder.app.start
        except ImportError:
            raise RuntimeError('Spyder is not installed')
        else:
            print('Running Spyder')
            spyder.app.start.main()
    elif args.jupyter:
        import sys
        sys.argv = ['']
        try:
            import notebook.notebookapp
        except ImportError:
            raise RuntimeError('Jupyter notebook is not installed')
        else:
            print('Running Jupyter')
            notebook.notebookapp.main()


if __name__ == '__main__':
    import sys
    main(*sys.argv[1:])
